#!/usr/bin/env bash

dtache_command="$*"

if eval script --quiet -e -c "\"$dtache_command\"" /dev/null; then
    echo -e "\nDtache session finished"
else
    echo -e "\nDtache session exited abnormally with code $?"
fi
